name: cp_awesome_flutter_cli
description: cp_awesome_flutter_cli
version: 1.0.0
homepage: https://github.com/yazicifatihcan/cp-awesome-flutter-cli.git

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  archive: ^3.3.0
  http: ^0.13.4


executables:
  cp_cli: cp_awesome_flutter_cli
  cp: cp_awesome_flutter_cli

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
